# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Cliente.create([
  { :nombres => nil, :apellidos => nil, :cedula => nil, :empresa => nil, :nit => nil, :cargo => nil, :telefono => nil, :direccion => nil, :celular => nil, :fax => nil, :email => nil, :municipio_id => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Contacto.create([
  { :nombre => nil, :apellido => nil, :telefono => nil, :celular => nil, :email => nil, :año => nil, :mes => nil, :dia => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Cotizacion.create([
  { :servicio_id => nil, :detalle_id => nil, :precio => nil, :total => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Departamento.create([
  { :nombre => "Antioquia", :sigla => "ANT", :created_at => "2013-09-10 05:01:52", :updated_at => "2013-09-10 05:01:52" }
], :without_protection => true )



Detalle.create([
  { :pieza => "5 a 10", :precio => 4000, :servicio_id => 1, :created_at => "2013-09-10 05:07:36", :updated_at => "2013-09-10 05:07:36" },
  { :pieza => "5 a 10", :precio => 6000, :servicio_id => 2, :created_at => "2013-09-10 05:08:13", :updated_at => "2013-09-10 05:08:13" }
], :without_protection => true )



Documento.create([
  { :created_at => "2013-09-10 05:55:41", :updated_at => "2013-09-10 05:56:52", :precios_file_name => "guia2.pdf", :precios_content_type => "application/pdf", :precios_file_size => 54785, :precios_updated_at => "2013-09-10 05:56:52" }
], :without_protection => true )



Municipio.create([
  { :nombre => "Itagui | Antioquia", :sigla => "Itg", :departamento_id => 1, :created_at => "2013-09-10 05:02:29", :updated_at => "2013-09-10 05:02:29" },
  { :nombre => "Envigado | Antioquia", :sigla => "Env", :departamento_id => 1, :created_at => "2013-09-10 05:02:50", :updated_at => "2013-09-10 05:02:50" }
], :without_protection => true )



Role.create([
  { :name => nil, :resource_id => nil, :resource_type => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Servicio.create([
  { :nombre => "patronaje basico", :created_at => "2013-09-10 05:03:58", :updated_at => "2013-09-10 05:03:58" },
  { :nombre => "escalado talla", :created_at => "2013-09-10 05:04:20", :updated_at => "2013-09-10 05:04:20" }
], :without_protection => true )



User.create([
  { :nombre => "Christiam Gomez", :telefono => nil, :username => "christiam", :email => "christiam@misena.edu", :crypted_password => "$2a$10$cdCv/Zs7hQqrEEREiKDqFO1hn3cDUTd6gfqthx6KfpemSBX2vrYnC", :salt => "uDV37o1Et4e1mzUfWdUa", :created_at => "2013-09-10 04:55:00", :updated_at => "2013-09-10 04:55:00", :remember_me_token => nil, :remember_me_token_expires_at => nil }
], :without_protection => true )


