# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Cliente.create([
  { :nombres => "juan", :apellidos => "gomez", :cedula => "123456687", :empresa => "", :nit => "", :cargo => "", :telefono => "45567788", :direccion => "cr 45 #45-67", :celular => "32147484848", :fax => "373834", :email => "juan@gmail.com", :municipio_id => 1, :created_at => "2013-09-11 05:31:42", :updated_at => "2013-09-11 05:31:42" },
  { :nombres => "juan", :apellidos => "gomez", :cedula => "123456687", :empresa => "", :nit => "", :cargo => "", :telefono => "45567788", :direccion => "cr 45 #45-67", :celular => "32147484848", :fax => "373834", :email => "juan@gmail.com", :municipio_id => 1, :created_at => "2013-09-11 05:33:11", :updated_at => "2013-09-11 05:33:11" },
  { :nombres => "calos", :apellidos => "suares", :cedula => "1234567", :empresa => "carlos.SA", :nit => "6785", :cargo => "gerente", :telefono => "45634657", :direccion => "cr 56 #67-43", :celular => "4566768", :fax => "345667", :email => "carlos@hotmail.com", :municipio_id => 2, :created_at => "2013-09-11 05:49:22", :updated_at => "2013-09-11 05:49:22" }
], :without_protection => true )



Contacto.create([
  { :nombre => "geraldine", :apellido => "arenas", :telefono => "3453465", :celular => "3212339941", :email => "geral@gmail.com", :año => 2013, :mes => 9, :dia => 11, :created_at => "2013-09-11 05:54:08", :updated_at => "2013-09-11 05:54:08" },
  { :nombre => "cristiam ", :apellido => "gomez", :telefono => "234567", :celular => "2334567889", :email => "cristiam@hotamail.com", :año => 2013, :mes => 5, :dia => 11, :created_at => "2013-05-11 05:52:30", :updated_at => "2013-09-11 05:52:30" }
], :without_protection => true )



Cotizacion.create([
  { :servicio_id => nil, :detalle_id => nil, :precio => nil, :total => nil, :created_at => nil, :updated_at => nil }
], :without_protection => true )



Departamento.create([
  { :nombre => "Antioquia", :sigla => "ANT", :created_at => "2013-09-10 05:01:52", :updated_at => "2013-09-10 05:01:52" }
], :without_protection => true )



Detalle.create([
  { :pieza => "5 a 10", :precio => 4000, :servicio_id => 1, :created_at => "2013-09-10 05:07:36", :updated_at => "2013-09-10 05:07:36" },
  { :pieza => "5 a 10", :precio => 6000, :servicio_id => 2, :created_at => "2013-09-10 05:08:13", :updated_at => "2013-09-10 05:08:13" }
], :without_protection => true )



Documento.create([
  { :created_at => "2013-09-10 05:55:41", :updated_at => "2013-09-10 05:56:52", :precios_file_name => "guia2.pdf", :precios_content_type => "application/pdf", :precios_file_size => 54785, :precios_updated_at => "2013-09-10 05:56:52" }
], :without_protection => true )



Municipio.create([
  { :nombre => "Itagui | Antioquia", :sigla => "Itg", :departamento_id => 1, :created_at => "2013-09-10 05:02:29", :updated_at => "2013-09-10 05:02:29" },
  { :nombre => "Envigado | Antioquia", :sigla => "Env", :departamento_id => 1, :created_at => "2013-09-10 05:02:50", :updated_at => "2013-09-10 05:02:50" }
], :without_protection => true )



Role.create([
  { :name => "admin", :resource_id => nil, :resource_type => nil, :created_at => "2013-09-11 03:26:38", :updated_at => "2013-09-11 03:26:38" }
], :without_protection => true )



Servicio.create([
  { :nombre => "patronaje basico", :created_at => "2013-09-10 05:03:58", :updated_at => "2013-09-10 05:03:58" },
  { :nombre => "escalado talla", :created_at => "2013-09-10 05:04:20", :updated_at => "2013-09-10 05:04:20" }
], :without_protection => true )



User.create([
  { :nombre => "christiam camilo", :telefono => nil, :username => "cristiam", :email => "Cristiam@misena.edu", :crypted_password => "$2a$10$AMfYgbo1897Jtrm7eEu/D./f82pide9xZ4E64RCfRWUtms0vnyoHm", :salt => "5fBSsxtX8vnPhuq26VTs", :created_at => "2013-09-11 04:29:40", :updated_at => "2013-09-11 04:29:40", :remember_me_token => nil, :remember_me_token_expires_at => nil }
], :without_protection => true )


